db:
  game:
    host: $DB_GAME_HOST
    user: $DB_GAME_USER
    pass: $DB_GAME_PASS
    port: $DB_GAME_PORT
    name: $DB_GAME_NAME

items_per_page: 20


servers:
  - id: "main"
    host: "game.yogstation.net"
    port: 4133
    name: "YogStation Main"

  - id: "atlas"
    host: "game.yogstation.net"
    port: 5133
    name: "YogStation Atlas"


logs:
  directory: "../Yogstation/data/logs/*/*/*"

links:
  forums: "https://forums.yogstation.net/"
  wiki: "https://wiki.yogstation.net/"

secret_key: $FLASK_SECRET_KEY

# KEEP THIS IN SYNC WITH THE GAME OR YOU WILL NOT BE ABLE TO EDIT BANS TO NEW ROLES IN GAME
roles: [
  "Captain",
  "Head of Personnel",
  "Head of Security",
  "Chief Engineer",
  "Research Director",
  "Chief Medical Officer",
  "Assistant",
  "Quartermaster",
  "Cargo Technician",
  "Shaft Miner",
  "Bartender",
  "Cook",
  "Botanist",
  "Janitor",
  "Clown",
  "Mime",
  "Curator",
  "Lawyer",
  "Chaplain",
  "Station Engineer",
  "Atmospheric Technician",
  "Medical Doctor",
  "Chemist",
  "Geneticist",
  "Virologist",
  "Scientist",
  "Roboticist",
  "Warden",
  "Detective",
  "Security Officer",
  "AI",
  "Cyborg",
  "Server",
  "Syndicate",
  "Traitor",
  "Operative",
  "Changeling",
  "Wizard",
  "Malf AI",
  "Revolutionary",
  "Head Revolutionary",
  "Xenomorph",
  "pAI",
  "Cultist",
  "Blob",
  "Space Ninja",
  "Monkey",
  "Abductor",
  "Revenant",
  "Devil",
  "Servant of Ratvar",
  "Blood Brother",
  "Brainwashed Victim",
  "Syndicate Mutineer",
  "Hivemind Host",
  "Obsessed",
  "Sentience Potion Spawn",
  "Mind Transfer Potion",
  "Posibrain",
  "Drone",
  "Deathsquad",
  "Lavaland",
  "Internal Affairs Agent",
  "Fugitive",
  "Shadowling",
  "Vampire",
  "Battle Royale Contestant",
  "gangster",
  "darkspawn",
  "Holoparasite",
  "Zombie"
]

library:
  categories: [
    "Any",
    "Fiction",
    "Non-Fiction",
    "Adult",
    "Reference",
    "Religion"
  ]